language: python

matrix:
  include:
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
      dist: xenial
      sudo: true

script:
  - python ./test_argparse.py

notifications:
  email:
    - key.mtrgtring@gmail.com